services:
  app:
    container_name: algopy_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app  # Mount the current directory to /app in the container
      - ./database/db:/app/database/db  # Mount the volume for finstore database